#pragma once
const int GRID_HEIGHT = 21;
const int GRID_WIDTH = 32;
const int GRID_CELL_SIZE = 20;
const int GAME_WINDOW_HEIGHT = GRID_HEIGHT * GRID_CELL_SIZE;
const int GAME_WINDOW_WIDTH = GRID_WIDTH * GRID_CELL_SIZE;

const int DEFAULT_TURN_DURATION_MS = 300;
const float SPEEDUP_RATIO = 0.98;